version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-ioasys
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ioasys_challenge
      - POSTGRES_USER=docker
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.6-alpine
    container_name: redis-ioasys
    tty: true
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo-ioasys
    tty: true
    ports:
      - "27017:27017"
